name: Update Requirements

on:
  pull_request:
  push:
    paths:
      - "poetry.lock"

jobs:
  export-requirements-txt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Poetry export
        run: |
          python -m pip install poetry
          poetry update
          poetry export -f requirements.txt --without-hashes --output requirements.txt
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build(requirements) Update requirements.txt"
