[logger]
level = "debug"
messageFormat = "%(asctime)s %(levelname)s %(message)s"

[server]
runOnSave = true

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans-serif"